# Generated by Django 4.1 on 2022-09-06 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cohort", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="answer_record",
            field=models.FileField(blank=True, null=True, upload_to="answer"),
        ),
        migrations.AddField(
            model_name="record",
            name="cohort_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_id",
                to="cohort.cohort",
            ),
        ),
    ]
