# Generated by Django 4.0.6 on 2022-08-11 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=200)),
                ('option1', models.CharField(max_length=80)),
                ('option2', models.CharField(max_length=80)),
                ('option3', models.CharField(max_length=80)),
                ('option4', models.CharField(max_length=80)),
                ('rightAnswer', models.CharField(max_length=80)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('mark', models.IntegerField()),
            ],
        ),
    ]
